server:
  port: 7002

spring:
  application:
    name: rule-service

  output:
    ansi:
      enabled: DETECT

  datasource:
    url: jdbc:mysql://0.0.0.0:3306/ruleservice
    username: root
    password: password
    dbcp2:
      validation-query: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

logging:
  level:
    #root: ERROR
    org.springframework.web: ERROR
    org.springframework.security: ERROR
    com.asiczen: ERROR
  file:
    name: rule-service.log
    max-size: 10 MB

